### ISSUE TITLE
使用来自 saveweb/rss-list 的域名列表

### ISSUE THREAD

**Issue by yzqzss** [txthinking/soso#12]
使用「[saveweb/rss-list](https://github.com/saveweb/rss-list)」 (Telegram: https://t.me/blogrsslist) 收录的独立博客&播客的域名。

目前已收录 1136 个博客&播客。

我们（@saveweb）一直在通过[订阅他们的 RSS 来观察这些站点](https://box.othing.xyz/)有没有变成“营销站”以及出现[宕机和换域名的情况](https://github.com/saveweb/doing/issues)，有问题我们会及时修改并把域名变化PR给上游（如果有的话，比如 https://github.xom/timqian/chinese-independent-blogs ） 。

所以这些域名应该可以加到 whitelist 中。😁

实时生成的opml订阅源： https://box.othing.xyz/realtime.opml.xml 格式是xml，如果不方便读取域名，有空我会写个小脚本转成一行一个域名的txt。除了“墓场轨道”这个分类（专门存放已关站的网站的分类），其它的域名都可以放心收录。

**Comment by txthinking** [comment]
有点疑惑
所有的 域名列表 或 rss/atom link 列表就是取

https://github.com/saveweb/rss-list/releases/download/V20201005/All.opml.xml

的xmlUrl值和htmlUrl对吧

**Comment by yzqzss** [comment]
暂时先不弄吧，我这边还有点问题，有些域名没有和实际域名对应。
